// Reads the custom properties in project/tokens/*.css. Used by the landing page,
// the lint and the SCSS export, so all three read the tokens the same way.

import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

/** The token files in the order styles.css imports them. */
export const TOKEN_FILES = ['fonts.css', 'colors.css', 'typography.css', 'shape.css', 'motion.css', 'spacing.css'];

/** Removes every @media and @keyframes block, braces and all, so overrides never read as the token. */
function stripAtBlocks(css) {
  let out = '';
  let i = 0;
  while (i < css.length) {
    const at = css.slice(i).search(/@(media|keyframes|supports)\b/);
    if (at < 0) { out += css.slice(i); break; }
    out += css.slice(i, i + at);
    let j = css.indexOf('{', i + at);
    if (j < 0) break;
    let depth = 1; j++;
    while (j < css.length && depth) { if (css[j] === '{') depth++; else if (css[j] === '}') depth--; j++; }
    i = j;
  }
  return out;
}

/** `--name: value; /* note *\/` → { name: { value, note } }, in source order. */
export function parseVars(css) {
  const out = {};
  const body = stripAtBlocks(css);
  for (const m of body.matchAll(/--([\w-]+)\s*:\s*([^;]+);[ \t]*(?:\/\*\s*([\s\S]*?)\s*\*\/)?/g)) {
    out[m[1]] = { value: m[2].trim().replace(/\s+/g, ' '), note: (m[3] || '').trim().replace(/\s+/g, ' ') };
  }
  return out;
}

/** Every token across the token files, keyed by name, with the file it came from. */
export function readTokens(dir) {
  const all = {};
  for (const f of TOKEN_FILES) {
    const vars = parseVars(readFileSync(join(dir, f), 'utf8'));
    for (const [k, v] of Object.entries(vars)) all[k] = { ...v, file: f };
  }
  return all;
}

/** Replaces var(--x) with x's value until none are left, so SCSS gets literals. */
export function resolveValue(value, all, seen = new Set()) {
  return value.replace(/var\(--([\w-]+)\)/g, (m, name) => {
    if (seen.has(name) || !all[name]) return m;
    return resolveValue(all[name].value, all, new Set([...seen, name]));
  });
}

/** The tokens as SCSS variables with the same names, for the website's src/styles. */
export function tokensToScss(dir) {
  const all = readTokens(dir);
  const lines = [
    '// Generated by the Obsydian design system build from project/tokens/*.css. Do not edit.',
    '// The website keeps these names in src/styles/_variables.scss; copy changes across from here.',
    '@use "sass:string";',
    '',
  ];
  let file = '';
  for (const [name, { value, file: f }] of Object.entries(all)) {
    if (f !== file) { if (file) lines.push(''); lines.push(`// ${f}`); file = f; }
    const v = resolveValue(value, all);
    // Sass reads a bare slash as division (the line height in a font shorthand), so quote those.
    const safe = /\//.test(v.replace(/url\([^)]*\)/g, '')) ? `string.unquote("${v.replace(/"/g, '\\"')}")` : v;
    lines.push(`$${name}: ${safe};`);
  }
  return lines.join('\n') + '\n';
}

export function listTokenFiles(dir) {
  return readdirSync(dir).filter((f) => f.endsWith('.css'));
}
